apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: word-count
  labels:
    strimzi.io/cluster: production-ready
spec:
  partitions: 4
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824